import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "DROTAVERISENE",
      slug: "METAPHELENE",
      category: "NMET",
      image: "/images/drotachem_inj.jpg",
      price: 26,
      brand: "Drotaverisine",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "METAPHELENE 250 MG NEFEMANIC ACID 80 MG",
      isFeatured: true,
      banner: "/images/banner1(1).jpg",
    },
    {
      name: "ACECLOFANAC SR 200 MG",
      slug: "YECLO 200 MG SR",
      category: "ORAL",
      image: "/images/2.jpg",
      price: 80,
      brand: "ACECLOFENAC",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "SR 200 MG",
      isFeatured: true,
      banner: "/images/banner2(1).jpg",
    },
    {
      name: "Amoxyceline and Potassium Clabulanat",
      slug: "Vinclav 620",
      category: "Tablet",
      image: "/images/3.jpeg",
      price: 15,
      brand: "Vinclav",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "Amoxyceline 500 MG and Potassium Clabulanat 125 MG",
    },
    {
      name: "SILODOSINE AND DUTASTERIDE ",
      slug: "DRIBSIL-D",
      category: "TABLET",
      image: "/images/4.jpeg",
      price: 3,
      brand: "DRIBSIL-D",
      rating: 5,
      numReviews: 13,
      countInStock: 20,
      description: "8 MG SILODOSINE AND 0.5 MG DUTASTERIDE",
    },
    {
      name: "MINOXIDIL 5% + FINASTERIDE TOPICAL SOLN",
      slug: "KERA-FM 5% TOPICAL SOLN",
      category: "LIQUID DROPPER",
      image: "/images/5.jpeg",
      price: 450,
      brand: "CUGARD",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "MINOXIDIL 5% + FINASTERIDE TOPICAL SOLN",
    },
    {
      name: "LEVOCETIRIZINE HCL 5MG & MONTELUKAST 10MG",
      slug: "MONTAIR LC",
      category: "ORAL",
      image: "/images/6.jpeg",
      price: 57,
      brand: "lIFE VISION",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "LEVOCETIRIZINE HCL 5MG & MONTELUKAST 10MG",
    },
    {
      name: "LOSARTAN POTASSIUM 25MG",
      slug: "CZAR 25MG",
      category: "ORAL",
      image: "/images/7.jpeg",
      price: 16,
      brand: "lIFE VISION",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "LOSARTAN POTASSIUM",
    },
  ],
};

export default data;
